export const NYX_GUIDE_STEPS = [
  {
    pose: 'welcome',
    kicker: 'Nyx',
    title: 'Tour rápido',
    lead: 'Hoje, evolução e conta.',
    note: 'Você pode pular.',
    chips: ['Hoje', 'Evolução', 'Conta'],
    targetLabel: 'Início',
    targetText: 'Abre as áreas principais.',
  },
  {
    pose: 'present',
    kicker: 'Hoje',
    title: 'Hoje',
    lead: 'Resumo do treino e da semana.',
    note: 'Bloco principal.',
    chips: ['Treino', 'Semana'],
    page: 'today',
    target: 'today-overview',
    targetLabel: 'Resumo do dia',
    targetText: 'Veja a sessão ativa e o que vem a seguir.',
  },
  {
    pose: 'present',
    kicker: 'Treino',
    title: 'Treino',
    lead: 'Blocos do dia em sequência.',
    note: 'Conteúdo do treino.',
    chips: ['Blocos'],
    page: 'today',
    target: 'today-workout',
    targetLabel: 'Blocos do treino',
    targetText: 'Warm-up, força, metcon e acessórios.',
  },
  {
    pose: 'curious',
    kicker: 'Importação',
    title: 'Importar treino',
    lead: 'PDF, imagem, vídeo, texto ou planilha.',
    note: 'Atalho de importação.',
    chips: ['PDF', 'Imagem', 'Vídeo', 'Texto'],
    page: 'today',
    target: 'today-import',
    targetLabel: 'Atalho de importação',
    targetText: 'Importe ou troque o treino atual.',
  },
  {
    pose: 'present',
    kicker: 'Evolução',
    title: 'Evolução',
    lead: 'Benchmarks e histórico.',
    note: 'Área de evolução.',
    chips: ['Benchmarks', 'PRs', 'Histórico'],
    page: 'history',
    target: 'history-benchmarks',
    targetLabel: 'Benchmarks e tendência',
    targetText: 'Veja referências e tendência.',
  },
  {
    pose: 'mentor',
    kicker: 'PRs',
    title: 'PRs',
    lead: 'Records pessoais no histórico.',
    note: 'Seção de PRs.',
    chips: ['PRs', 'Referências', 'Progressão'],
    page: 'history',
    target: 'history-prs',
    targetLabel: 'Seção de PRs',
    targetText: 'Registre e acompanhe cargas.',
  },
  {
    pose: 'mentor',
    kicker: 'Conta',
    title: 'Conta',
    lead: 'Acesso, portal e atividade.',
    note: 'Visão geral da conta.',
    chips: ['Acesso', 'Status', 'Portal'],
    page: 'account',
    accountView: 'overview',
    target: 'account-access',
    targetLabel: 'Visão geral da conta',
    targetText: 'Status e atalhos principais.',
  },
  {
    pose: 'mentor',
    kicker: 'Coach',
    title: 'Portal',
    lead: 'Acesso do coach no mesmo login.',
    note: 'Entrada do portal.',
    chips: ['Portal', 'Acesso'],
    page: 'account',
    accountView: 'overview',
    target: 'account-coach',
    targetLabel: 'Entrada do Coach Portal',
    targetText: 'Veja status e abertura do portal.',
  },
  {
    pose: 'present',
    kicker: 'Preferências',
    title: 'Preferências',
    lead: 'Aparência, treino e Nyx.',
    note: 'Ajustes do app.',
    chips: ['Aparência', 'Densidade', 'Treino', 'Nyx'],
    page: 'account',
    accountView: 'preferences',
    target: 'account-preferences',
    targetLabel: 'Preferências',
    targetText: 'Mude visual, densidade e leitura.',
  },
  {
    pose: 'mentor',
    kicker: 'Dados',
    title: 'Dados',
    lead: 'Backup e documentos.',
    note: 'Área de dados.',
    chips: ['Backup', 'Documentos', 'Migração'],
    page: 'account',
    accountView: 'data',
    target: 'account-data',
    targetLabel: 'Dados e backup',
    targetText: 'Exporte, restaure e revise o acesso.',
  },
  {
    pose: 'rest',
    kicker: 'Pronto',
    title: 'Pronto',
    lead: 'Você já viu as áreas principais.',
    note: 'Volta ao início.',
    chips: ['Hoje', 'Conta'],
    page: 'today',
    target: 'today-overview',
    targetLabel: 'Volta ao começo',
    targetText: 'Siga pelo Hoje ou abra conta e evolução.',
  },
];

export function getNyxGuideStepCount() {
  return NYX_GUIDE_STEPS.length;
}

export function clampNyxGuideStep(step) {
  const index = Number(step);
  if (!Number.isInteger(index)) return 0;
  return Math.min(Math.max(index, 0), NYX_GUIDE_STEPS.length - 1);
}

export function getNyxGuideStep(step) {
  return NYX_GUIDE_STEPS[clampNyxGuideStep(step)] || NYX_GUIDE_STEPS[0];
}
